name: "Snapclient"
description: "Use your Home Assistant server as a Snapcast client"
version: "0.1.0"
slug: "snapclient"
init: false
audio: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  host: "127.0.0.1"
  port: 1704
schema:
  host: str
  port: int
